name: alpine-bootstrap-repo

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.23

    steps:
      - name: set repositories + update
        run: |
          echo "https://dl-cdn.alpinelinux.org/alpine/v3.23/main" > /etc/apk/repositories
          echo "https://dl-cdn.alpinelinux.org/alpine/v3.23/community" >> /etc/apk/repositories
          apk update

      - name: install tools
        run: |
          apk add --no-cache git apk-tools ca-certificates

      - uses: actions/checkout@v4

      - name: fetch base packages (recursive)
        run: |
          mkdir -p repo/x86_64
          apk fetch --recursive \
            --repository https://dl-cdn.alpinelinux.org/alpine/v3.23/main \
            --repository https://dl-cdn.alpinelinux.org/alpine/v3.23/community \
            --arch x86_64 \
            --output repo/x86_64 \
            musl busybox nano
          apk index -o repo/x86_64/APKINDEX.tar.gz repo/x86_64/*.apk

      - name: commit & push to main
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          cp -r repo/* .

          git add .
          git commit -m "update alpine bootstrap repo" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
