name: alpine-bootstrap-repo

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.23

    steps:
      - name: set repositories + update
        run: |
          echo "https://dl-cdn.alpinelinux.org/alpine/v3.23/main" > /etc/apk/repositories
          echo "https://dl-cdn.alpinelinux.org/alpine/v3.23/community" >> /etc/apk/repositories
          apk update

      - name: install tools
        run: |
          apk add --no-cache \
            git \
            apk-tools \
            ca-certificates

      - uses: actions/checkout@v4

      - name: fetch base packages
        run: |
          mkdir -p repo/x86_64
          apk fetch \
            --repository https://dl-cdn.alpinelinux.org/alpine/v3.23/main \
            --repository https://dl-cdn.alpinelinux.org/alpine/v3.23/community \
            --arch x86_64 \
            --output repo/x86_64 \
            musl \
            busybox \
            libncurses \
            nano

      - name: generate index
        run: |
          apk index -o repo/x86_64/APKINDEX.tar.gz repo/x86_64/*.apk

      - name: publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: repo
